# This file was generated by GoReleaser. DO NOT EDIT.
cask "chatwright" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "91b85ffb0e720e52a242413a399a1782661e7f7615dc9c89e1bbd7a0c74c3c86"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "276692be2d5ad81eb91fdcb6dd8955c94e896f52869618e8192aa9c3e5f4b4c5"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "32ae3e1cc5378a7a89a8cf6e19654b5cdde040460cdc9e051f4c3ed7e49153c2"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd04a9560c63b7f66ccc2f547f49b823a653015ab523eb97153e65546718ebfc"
      url "https://github.com/chatwright/cli/releases/download/v#{version}/chatwright_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chatwright"
  desc "Chatwright CLI — deterministic and AI-driven testing for conversational applications."
  homepage "https://chatwright.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chatwright"

  # No zap stanza required

end
