# This file was generated by GoReleaser. DO NOT EDIT.
cask "codegrapher" do
  version "0.12.0"

  on_macos do
    on_arm do
      sha256 "a24e9c4b004053b205eda9024af8fe1b839f7cd69347f85a005ddf2bf1917ec5"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb4c440e2470bfe8d3966f475eaff4c69246cde75a90bc8604d7ac436e39bca5"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a3b78a2a72fa9e02ec543cc34043fb6bbebb7a2d6b8aa19e67b78ea0172d748a"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3fa6b12e5a22373e1c7a0f8e082f92f4ef2dc53c46555f59112a74fa4081aaa7"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_linux_amd64.tar.gz"
    end
  end

  name "codegrapher"
  desc "codegrapher – a free Go tool that builds a graph of your codebase"
  homepage "https://github.com/code-grapher/codegrapher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codegrapher"

  # No zap stanza required
end
