# This file was generated by GoReleaser. DO NOT EDIT.
cask "datatug" do
  version "0.30.0"

  on_macos do
    on_arm do
      sha256 "362abe434d47f55cf8f0d7e14b5dc1f53bc9421180227a2e422ee14fe3cb6032"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "07a46799ffebf615bba1ecb757945103ffabb3c930f09c152b3efde76fc66dc6"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "74ccb77d404dad0cc89ba4595b0c44d7d6c8aee1853241db31ac3e0bbea3046a"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2826be3e2182f29daa0685c5b5a38a462eae7cdcee0cc5f0216897b5da0ac18b"
      url "https://github.com/datatug/datatug-cli/releases/download/v#{version}/datatug_#{version}_linux_amd64.tar.gz"
    end
  end

  name "datatug"
  desc "DataTug – Context-aware data viewer & collaborative query manager for effortless exploration of related data — CLI + Web UI"
  homepage "https://github.com/datatug/datatug-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "datatug"

  # No zap stanza required
end
