# This file was generated by GoReleaser. DO NOT EDIT.
cask "ingitdb" do
  version "0.65.16"

  on_macos do
    on_arm do
      sha256 "0fa99ad129a834f6a4df0152d146004d78211477444ce03276f8fcfe7d1a783d"
      url "https://github.com/ingitdb/ingitdb-cli/releases/download/v#{version}/ingitdb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f018eb2e05eb53a5052e60c444cce4ec15d5f05a5cf28dbdebcdec78cd1eee5c"
      url "https://github.com/ingitdb/ingitdb-cli/releases/download/v#{version}/ingitdb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "959f6cc1d130d2874db56ec9bb9bbfb26ebc3bf895a53a54f50073f03380e227"
      url "https://github.com/ingitdb/ingitdb-cli/releases/download/v#{version}/ingitdb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "853391b4f0b11ebe9da1464a83ec6c13638fa4f0e40ca8b79b74be3485c05f5e"
      url "https://github.com/ingitdb/ingitdb-cli/releases/download/v#{version}/ingitdb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ingitdb"
  desc "ingitdb – a CLI for a developer-grade, schema-validated, AI-native database whose storage engine is a Git repository."
  homepage "https://ingitdb.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ingitdb"

  # No zap stanza required
end
