# This file was generated by GoReleaser. DO NOT EDIT.
cask "ovdb" do
  version "0.12.0"

  on_macos do
    on_arm do
      sha256 "47d0c6557f8936a598812d93f446df7ec768ded17d5b0ed4fb186b1773c5e63b"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9639b9c1bcf684a9b880997c00c5bcece15214813a58fe258eac9233a358076e"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e8b819f00991ab48595eba8b5a2509e7c95b18976358555c8655528cd0ace685"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d0dfb6b5e2590849349d5e06582d5c4fb52b2547d5f9eb1b619da0f8585b3c1"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ovdb"
  desc "ovdb — the OpenVaultDB command-line interface"
  homepage "https://github.com/openvaultdb/openvaultdb-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ovdb"

  # No zap stanza required
end
