# This file was generated by GoReleaser. DO NOT EDIT.
cask "sneat" do
  version "0.14.0"

  on_macos do
    on_arm do
      sha256 "68678ca3ca900e358dd7977e2f1912a481d694e2aa2680acfdfc906ec7f447c5"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ab528e9c285cb95d10b1419363c93760d91fec2d827b07a52daf169dc193a120"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "56bdbde42d57ce5f1a3a92f71e981f4c20f8f3965d14b73a1c187bbcb01b65d6"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ec37bd9a035d20f4443a9b8f8c31516c04cec185d21a99621015bf41bb988aa1"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sneat"
  desc "sneat - Text-based User Interface for Sneat.app"
  homepage "https://sneat.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sneat"

  # No zap stanza required
end
