# This file was generated by GoReleaser. DO NOT EDIT.
cask "specscore" do
  version "0.52.0"

  on_macos do
    on_arm do
      sha256 "7fb0b2afde7f8ed17df780b481a1bcbd708f135773899beb466c95a669b2b9c2"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "20d54d634e06be3cc36195487313cfd7f97d6fd19dc03e33db15592916981c4b"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "11fe29c4c6a2d91a69b0e7fdf48a2ca3d15b83d43631100a6249958e9051b66b"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "609c596a3998d5448dacffd5f07911a0f7770471ec6178ff09d34f98ca53ba89"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_linux_amd64.tar.gz"
    end
  end

  name "specscore"
  desc "SpecScore CLI — lint, validate, and navigate Markdown specifications."
  homepage "https://specscore.md"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specscore"

  # No zap stanza required
end
