# This file was generated by GoReleaser. DO NOT EDIT.
cask "wb" do
  version "0.135.0"

  on_macos do
    on_arm do
      sha256 "161276ba658402819e929ada5cf25520741f24db7589b833fbaa6437bcb9802f"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e2a8cfb702b89d4cc6925a1b88a48cc09454b0636e64e4356b5924bed74a4b7a"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3becfb3c30d5cd6ddb79a00c32bfae4140116d3982dd7639182b8941a0ea6094"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "104be9791847471306c0125c225fdd3f4a96973d90417b5cc3dc73652329886e"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wb"
  desc "wb — the Sneat workbench CLI: fleet-wide GitHub repo sync and config-driven recipes."
  homepage "https://sneat.work/bench"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wb"

  # No zap stanza required
end
